import type { NextPage } from 'next'
import Head from 'next/head'

import { useLocale } from '../hooks/useLocale'

import { Locale } from '../types/localization'
import { Layout } from '../layouts'

const Home: NextPage = () => {
  const { changeLocale } = useLocale()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <a onClick={() => changeLocale(Locale.EN)}>{Locale.EN}</a>
        <a onClick={() => changeLocale(Locale.RU)}>{Locale.RU}</a>
      </Layout>
    </>
  )
}

export default Home
