import type { NextPage } from 'next'
import Head from 'next/head'

import { useLocale } from '../hooks/useLocale'
import { Page } from '../layouts/Page'
import { Locale } from '../types/localization'

const Home: NextPage = () => {
  const { changeLocale } = useLocale()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Page>
        <div onClick={() => changeLocale(Locale.EN)}>{Locale.EN}</div>
        <div onClick={() => changeLocale(Locale.RU)}>{Locale.RU}</div>
      </Page>
    </>
  )
}

export default Home
